spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/travel_db
    password: root123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        temp:
          use_jdbc_metadata_defaults: 'false'
    show-sql: 'true'
    hibernate:
#            ddl-auto: create
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
hashId:
  salt: Aut0(redit2@File
  length: 8
  alphabet: DdAa5Bb4Ii3Yy2Cc1UuMmRrSsFfOoLlWwKkQqXxHhEeVv0Tt6Zz7Pp8Gg9NnJj
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000000
      refresh-token:
        expiration: 6048000000

